### ISSUE TITLE
Add option to disable scrolling of the minimap

### ISSUE THREAD

**Issue by mike-lischke** [stefanceriu/SCXcodeMiniMap#40]
Hi, can you please add the option to avoid scrolling the minimap? Instead show the entire file fully in the minimap. This scrolling is not only distracting but gives completely wrong feedback when clicking in the minimap to go to specific locations. Because of the scrolling the area of interest goes out of view or at least moves up or down - but always away form the cursor. I recommend to have a look at the same feature in Visual Studio. There's it's really well done.

**Comment by stefanceriu** [comment]
I'm not entirely sure that's a good idea, showing even more text in the mini map will force Xcode to syntax highlight more text, which in turn will make is slower.
It will also make the text in the mini map very small as you would need to cram more of it in there.
You can play around with the size slider to whatever suits your needs but it will definitely not look good on large source files.

**Comment by mike-lischke** [comment]
The keypoint here is probably to show only part of the source file, depending on the overall length. For instance show only every second or third line or merge the colors of 2-3 lines into one and just draw a line in the minimap. You don't print real text there anyway, right? I really recommend to have a look at Visual Studio 2013. There's a very implementation of this feature..

**Comment by stefanceriu** [comment]
I see what you mean now although I'm not really sure how I can pull that off. I do actually display real text in there, the mini map and the main editor are hooked into the same text storage. The only things that are different between them are the colors, and only because those are drawn as temporary attributes, not affecting the storage. If I go and merge lines together I risk loosing the built in syntax highlighting, which I really don't want to do :)

I understand that VS has a nice implementation, the whole thing is pretty damn cool, but they have an advantage I don't.. access to real code without stumbling around in the dark and dumped private headers. 

I will definitely keep your suggestion in mind, but realistically, it probably won't become a thing any time soon.

**Comment by mike-lischke** [comment]
I fully understand the limitations you are facing and I'm sure you will do your best. But with that scrolling I cannot use minimap atm. But maybe there are more supporters for my wish which will make a difference in the future :-) So keep this as feature request for a later date. Thanks anyway.

**Comment by stefanceriu** [comment]
Will do, thank you too for the interesting talk :+1:
