### ISSUE TITLE
Blinking selection

### ISSUE THREAD

**Issue by gerchicov-bp** [stefanceriu/SCXcodeMiniMap#64]
It is hard to use it because it blinks each time I add a new line to the document or show/hide the autocompletion help on esc command or similar actions. And it is annoying

**Comment by stevemoser** [comment]
I have a similar issue but I get screen tearing while scrolling around the 40 char mark on a retina screen and Xcode 6.

**Comment by stefanceriu** [comment]
It's blinking because of a delayed invalidations, which I have added to prevent it from crippling down Xcode. I am aware it's not ideal but I couldn't find any other way to get it working.
If you have a better idea I would be more than happy to accept a pull request but in the mean time, I am closing the issue.
