### ISSUE TITLE
Causes scroll position to jump unexpectedly

### ISSUE THREAD

**Issue by Jiropole** [stefanceriu/SCXcodeMiniMap#68]
I really like and appreciate your work on this plugin! But I have an issue that may force me to uninstall it. 

While switching between previous/next documents, it seems like the plugin will cause the scroll position to jump unexpectedly, so I'm no longer looking at the same section when I return to a given file. Seems to be exacerbated by changes in the editor window height, i.e. due to hiding/revealing the console.

This same issue is easiest to reproduce by doing a global search, aside from any changes to editor heigh. Clicking on search results will sometimes bring you to the wrong scroll position in the target file; clicking again corrects this. Seems to happen most with longer code files, 300 lines+.

**Comment by stefanceriu** [comment]
I saw the same problem a while back and I think I fixed it on develop, bundled together with autohiding for the version and comparison editors.
Can you please check that version and let me know ?

**Comment by winkelsdorf** [comment]
I am encountering the same problem and would suggest reopening this issue. Using latest version via Alcatraz.

Steps to reproduce:
- Open a source file larger than screen
- Set cursor to a line somewhere near the bottom of the file
- Run (i.e. let Xcode automatically open Debugger console)

Expected:
- Scroll position is unchanged
- Current line with the blinking cursor is out of view (due to Debugger being shown)
- Hiding debugger should reveal the unchanged cursor position

Using Minimap:
- Scroll position jumps to somewhere in the middle of the file
- Cursor is still at the previous position (at least this is correct)

hth!
